///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Avianca
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the AviancaRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
    [RepositoryFolder("c84fb135-f1e1-4ec8-af2e-18e63ef4015f")]
    public partial class AviancaRepository : RepoGenBaseFolder
    {
        static AviancaRepository instance = new AviancaRepository();

        /// <summary>
        /// Gets the singleton class instance representing the AviancaRepository element repository.
        /// </summary>
        [RepositoryFolder("c84fb135-f1e1-4ec8-af2e-18e63ef4015f")]
        public static AviancaRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public AviancaRepository() 
            : base("AviancaRepository", "/", null, 0, false, "c84fb135-f1e1-4ec8-af2e-18e63ef4015f", ".\\RepositoryImages\\AviancaRepositoryc84fb135.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("c84fb135-f1e1-4ec8-af2e-18e63ef4015f")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
    public partial class AviancaRepositoryFolders
    {
    }
#pragma warning restore 0436
}